// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;
// import 'firebase_options.dart';

// / Default [FirebaseOptions] for use with your Firebase apps.
// /
// / Example:
// / ```dart
// / import 'firebase_options.dart';
// / // ...
// / await Firebase.initializeApp(
// /   options: DefaultFirebaseOptions.currentPlatform,
// / );
// / ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCfFVnzxVEtD6HpzIkoYlbATHI_4piTHg0',
    appId: '1:77031990442:web:2ad31cfad75d4159705cd3',
    messagingSenderId: '77031990442',
    projectId: 'gucchhu-58835',
    authDomain: 'gucchhu-58835.firebaseapp.com',
    storageBucket: 'gucchhu-58835.appspot.com',
    measurementId: 'G-8994L0WYE6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAFF6roOI68KAob5ADHp7JUi3N45OcZkGI',
    appId: '1:77031990442:android:b070928f9148de5e705cd3',
    messagingSenderId: '77031990442',
    projectId: 'gucchhu-58835',
    storageBucket: 'gucchhu-58835.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDpAiMOmWZ5Fyc4owZVl9lWe0rZ-KAJmME',
    appId: '1:77031990442:ios:f433deb5a8a03cf9705cd3',
    messagingSenderId: '77031990442',
    projectId: 'gucchhu-58835',
    storageBucket: 'gucchhu-58835.appspot.com',
    iosClientId:
        '77031990442-m055b0jnn9odp8anmc57jrsv99dq41rt.apps.googleusercontent.com',
    iosBundleId: 'com.example.gucchu',
  );
}
